### ISSUE TITLE
Bug: Supabase magic link leads to 404 page

### ISSUE THREAD

**Issue by sueszli** [sueszli/matchy#33]
This bug occurs when trying to register on github pages because supabase forwards you to the wrong page.

One possible fix would be buying a domain (which we could also register in AWS SES)

**Comment by MJDeligan** [comment]
This should have been fixed by #31 , which also allows us to develop locally, redirecting us to localhost instead of gh-pages.

**Comment by sueszli** [comment]
@MJDeligan Awesome job - thank you <3

**Comment by sueszli** [comment]
Whoops - still doesn't work on mobile phones on the deployed page

**Comment by MJDeligan** [comment]
Doesn't work on desktop either.

The redirect link goes to [https://sueszli.github.io/](https://sueszli.github.io/) which is missing the `/matchy` path.

**Comment by sueszli** [comment]
Ok yeah - this is because the supabase website doesn't forward you to concrete paths even if you state them.

The only way to fix this is to buy a domain.

**Comment by sueszli** [comment]
I'm gonna do that as soon as we implemented the core features.

**Comment by MJDeligan** [comment]
Apparently redirects do work with magic links, see [https://github.com/supabase/supabase/issues/4540](https://github.com/supabase/supabase/issues/4540). The only thing that doesn't work is wild-cards, but our redirects are, for now, hardcoded anyways, right?

It's definitely good to have a domain, but we could try adding back the redirect in the sign in for now.

**Comment by sueszli** [comment]
Lmfao now it all adds up - that's why it suddenly stopped working.

We removed the`redirectTo` because we thought it's useless.

**Comment by MJDeligan** [comment]
Yeah, their documentation is kind of misleading on that one...

**Comment by stefnotch** [comment]
I wonder what the most elegant way of dealing with this would be.
Ideally, we could set `redirectTo` to something like `https://sueszli.github.io/matchy/#/callback?`, but that might be a bit tricky to pull off without hardcoding it.
Parts of the URL
- Domain: Easy to get, just remember to also handle domains with a port. Using `window.location.origin` seems to be the right way to go
- Base path: Not sure how to *not* hardcode the `matchy` part. 
- Hash mode: The fact that we're using hash URLs `#`, because GitHub pages is somewhat limited, also needs to be dealt with accordingly
- Path: Ideally we could redirect to a path like `/callback`
- Question mark or hash: The `?` or `#` seems to not get automatically added by Supabase

**Comment by stefnotch** [comment]
I guess this might work if we want to avoid hardcoding it:
```ts
new URL(
      router.resolve("/callback").href,
      new URL(import.meta.env.BASE_URL, window.location.origin)
    )
```

**Comment by sueszli** [comment]
@stefnotch woah ... you really did a lot of research for this issue.
Thank you man <3

**Comment by sueszli** [comment]
Glad we could resolve it without buying a custom domain and getting rid of paths ^^ awesome stuff

**Comment by sueszli** [comment]
@MJDeligan @stefnotch am i allowed to close this issue? :0
